import random

noun = input("NOUN")
adjective = input("ADJECTIVE")
chooseanumber = input("CHOOSE A NUMBER")
adverbendinginly= input("Adverb Ending in -ly")
placename1=input("Place Name")
placename2=input("Place Name")
smallnumber=input("Small Number")
celebrityname=input("Celebrity Name")
nounfortypeofprofession=input("Noun for type of Profession")
bodypart=input("Body Part")
adverb=input("Adverb")
anothernoun=input("Another Noun")
largenumber=input("Large Number")
onemorenoun=input("One more Noun")
anyweatherterm=input("Any Weather Term!")
animal=input("Animal").upper()
bird=input("Bird")
food=input("Food")
print("We had a dream.To make a " +  (noun) +  " project.Together with a bunch of " + (adjective) +" "+ (noun) + "."+ " We came together on this journey of " + (chooseanumber)  + " weeks." )
print("This was the first time! Excitement was "+ (adjective)+"."+ "We " +(adverbendinginly)+ " looked forward to the "+( adjective)+ " project.")
print("People had joined in from "+ (placename1)+ " and " +(placename2)+"."+ "There were "+(smallnumber)+  " of us. Nobody knew how to start. But, deep within we were all "+(celebrityname) +"-"+  (nounfortypeofprofession)+"." + "We believed we could find the way. We talked, scoured the internet for ideas, took inspiration from our hearts. Finally, we found the " + (noun) + ".")
print("One that was close to our "+ (bodypart) +"."+ "We wanted to create a " + (adjective) + " project. It would be a story with blanks left for users to fill in. Thus, every user would make their unique story. The project would display text " + (adverb)+ "." + "on the " + (noun) + " and another " + (noun) + " would search for some customized images from the internet. What a " + (adjective) + " customer experience it would be. A fun outing for children of all ages," + (smallnumber) + " to " + (largenumber) +".That was the dream.")
print("We planned to use " + (noun) + "," + (onemorenoun) + " and "+ (anothernoun) + " to create the project. Running the project in a/an "+ (adjective) + " way. It was all new, by the way." )
print("Each one set out to do their part. Progress was very " + (adjective) + "." + " Time was running " + (adjective)+ ". Deadlines to be " + (adjective) + ". So many pieces of the " + (noun) + " were unknown. We knew we could be lost. We kept trying every day. Little by Little. Slowly the project developed in parts. Then, came the " + (anyweatherterm)+ "! The project came to life." + (animal) +"," +(bird) +","+ (food)+ " or " + (bodypart) + "- all could be seen on screen!" )
print("We were " + (adverbendinginly) + " all so happy. So "+ (adjective) +". A dream journey was accomplished. ")